export enum AlbumsActionTypes {
  GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST',
  GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS',
  GET_ALBUMS_FAILURE = 'GET_ALBUMS_FAILURE',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  REMOVE_ALBUMS = 'REMOVE_ALBUMS',
}
