export enum TracksActionTypes {
  GET_TRACKS_REQUEST = 'GET_TRACKS_REQUEST',
  GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS',
  GET_TRACKS_FAILURE = 'GET_TRACKS_FAILURE',
  REMOVE_TRACKS = 'REMOVE_TRACKS',
}
