export enum AlbumViewActionTypes {
  GET_ALBUM_VIEW_REQUEST = 'GET_ALBUM_VIEW_REQUEST',
  GET_ALBUM_VIEW_SUCCESS = 'GET_ALBUM_VIEW_SUCCESS',
  GET_ALBUM_VIEW_FAILURE = 'GET_ALBUM_VIEW_FAILURE',
  UPDATE_ALBUM_VIEW = 'UPDATE_ALBUM_VIEW',
}
